spring:
  application:
    name: Banking-Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Banking-Bank-Service
          uri: lb://Banking-Bank-Service
          predicates:
            - Path=/bank/**
          filters:
            - StripPrefix=1
        - id: Banking-User-Service
          uri: lb://Banking-User-Service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: Banking-Fund-Transfer-Service
          uri: lb://Banking-Fund-Transfer-Service
          predicates:
            - Path=/fund/**
          filters:
            - StripPrefix=1
        - id: Banking-Utility-Payment-Service
          uri: lb://Banking-Utility-Payment-Service
          predicates:
            - Path=/utilityPayment/**
          filters:
            - StripPrefix=1
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka